#  2D PBR - Dispersion model - only heat conduction - OCC

## Equations

The governing equation in dimensional form:
$$
U \:  \rho_f \: c_p \frac{\partial T}{\partial z} = -\frac{\lambda_{\text{r}}}{r} \frac{\partial}{\partial r} \left( r \frac{\partial T}{\partial r} \right)
$$

The dimensionless form:
$$
\frac{\partial \theta}{\partial \zeta} = -\frac{1}{\text{Pe}_R} \: \frac{1}{\phi} \: \frac{\partial}{\partial \phi} \left( \phi \frac{\partial \theta}{\partial \phi} \right)
$$
where:
$$
\theta = \frac{T}{T_{\text{ref}}}, \quad 
\zeta = \frac{z}{L}, \quad 
\phi = \frac{r}{R}, \quad 
\text{Pe}_R = \frac{\rho_f \: c_p \: U \: R}{\lambda_{\text{r}}}
$$

The approximation of $\theta$ using an orthogonal polynomial expansion:
$$
\tilde{\theta} (\phi (\zeta) )= \alpha_0 + \alpha_1 \: \phi + \alpha_2 \: \phi^2 + \cdots + \alpha_n \: \phi^n
$$
with the roots of the shifted Legendre polynomial as the internal collocation points:

<img src="collocation_points.png">

the trial function for a single collocation point $i$:
$$
\tilde{\theta}_i (\phi_{i} (\zeta))= \alpha_0 + \alpha_1 \; \phi_i + \alpha_2 \; \phi_{i}^2 + \cdots + \alpha_n \; \phi_{i}^n
$$
with $i=1,\: 2, \: ... , \:n+1$

or equivalently:
$$
\tilde{\theta}_i(\phi (\zeta) ) = 
\begin{bmatrix}
    1 & \phi_{i} & \phi_{i}^2 & \cdots & \phi_{i}^n
\end{bmatrix}
\begin{bmatrix}
    \alpha_0 \\
    \alpha_1 \\
    \alpha_2 \\
    \vdots \\
    \alpha_n
\end{bmatrix}
$$




In matrix form:
$$
\begin{pmatrix}
\theta_1 \\
\theta_2 \\
\theta_3 \\
\vdots \\
\theta_n \\
\theta_{n+1}
\end{pmatrix}
=
\begin{pmatrix}
\phi_1^0 & \phi_2^1 & \phi_1^2 &  \phi_1^3 & \cdots & \phi_1^{n-1} & \phi_1^n \\
\phi_2^0 & \phi_3^1 & \phi_2^2 & \phi_2^3 & \cdots & \phi_2^{n-1} & \phi_2^n \\
\phi_3^0 & \phi_4^1 & \phi_3^2 & \phi_3^3 & \cdots & \phi_3^{n-1} & \phi_3^n \\
\vdots&\vdots &\vdots & \vdots& \ddots & \vdots & \vdots \\
\phi_n^0 & \phi_n^1 & \phi_n^2 & \phi_n^3 & \cdots & \phi_n^{n-1} & \phi_n^n \\
\phi_{n+1}^0 & \phi_{n+1}^1 & \phi_{n+1}^2 & \phi_{n+1}^3 & \cdots & \phi_{n+1}^{n-1} & \phi_{n+1}^n
\end{pmatrix}
\begin{pmatrix}
\alpha_0 \\
\alpha_1 \\
\alpha_2 \\
\vdots \\
\alpha_{n-1} \\
\alpha_n
\end{pmatrix}
$$

in Matrix notation:
$$\gamma = \mathbf{Q} \; f $$
and thus:
$$ f = \mathbf{Q}^{-1} \; \gamma $$


the first derivative at collocation point i:

\begin{equation}
    \frac{\partial \tilde{\theta}(\phi_i)}{\partial \phi} = 
    \begin{bmatrix}
        0 & 1 & 2\phi_i & 3\phi_i^2 & \cdots & n\ \; \phi_i^{n-1}
    \end{bmatrix}
    \begin{bmatrix}
        \alpha_0 \\
        \alpha_1 \\
        \alpha_2 \\
        \vdots \\
        \alpha_n
    \end{bmatrix} 
    = \\
    \begin{bmatrix}
        0 & 1 & 2\phi_i & 3\phi_i^2 & \cdots & n\ \; \phi_i^{n-1}
    \end{bmatrix} \; \textbf{Q}^{-1} \; \gamma
\end{equation}

\begin{equation}
    [s^{(i)}]^T = 
    \begin{bmatrix}
        0 & 1 & 2\phi_i & 3\phi_i^2 & \cdots & n\ \; \phi_i^{n-1}
    \end{bmatrix} \; \textbf{Q}^{-1}
\end{equation}
$(n+1) \times (n+1)$ matrix for the first derivative:
\begin{equation}
    S = \begin{bmatrix}
        [s^{(1)}]^T \\
        [s^{(2)}]^T \\
        \vdots \\
        [s^{(n)}]^T \\
        [s^{(n+1)}]^T
    \end{bmatrix}
\end{equation}


for the second derivative:

\begin{equation}
    \frac{\partial^2 \tilde{\theta}(\phi_i)}{\partial \phi^2} = 
    \begin{bmatrix}
        0 & 2 & 6\phi_i & 12\phi_i^2 & \cdots & n(n-1)\ \; \phi_i^{n-2}
    \end{bmatrix}
    \begin{bmatrix}
        \alpha_0 \\
        \alpha_1 \\
        \alpha_2 \\
        \vdots \\
        \alpha_n
    \end{bmatrix} 
    = \\
    \begin{bmatrix}
        0 & 2 & 6\phi_i & 12\phi_i^2 & \cdots & n(n-1)\ \; \phi_i^{n-2}
    \end{bmatrix} \; \textbf{Q}^{-1} \; \gamma
\end{equation}

\begin{equation}
    [t^{(i)}]^T = 
    \begin{bmatrix}
        0 & 2 & 6\phi_i & 12\phi_i^2 & \cdots & n(n-1)\ \; \phi_i^{n-2}
    \end{bmatrix} \; \textbf{Q}^{-1}
\end{equation}

The $(n+1) \times (n+1)$ matrix for the second derivative:
\begin{equation}
    T = \begin{bmatrix}
        [t^{(1)}]^T \\
        [t^{(2)}]^T \\
        \vdots \\
        [t^{(n)}]^T \\
        [t^{(n+1)}]^T
    \end{bmatrix}
\end{equation}


### Discretized Differential Equation Using Orthogonal Collocation

The original PDE (after applying product rule):
$$
\frac{\partial \theta}{\partial \zeta} = -\frac{1}{\text{Pe}_R} \left( \frac{\partial^2 \theta}{\partial \phi^2} + \frac{1}{\phi} \frac{\partial \theta}{\partial \phi} \right)
$$

Discretized form using orthogonal collocation yields a system of ODE's. 
$$
\frac{d\boldsymbol{\theta}_i}{d\zeta} = -\frac{1}{\text{Pe}_R} \left( [t^{(i)}]^T \: \boldsymbol{\theta_i}(\zeta) + \frac{1}{\phi} \: [s^{(i)}]^T \:\boldsymbol{\theta_i}(\zeta) \right)
$$
or in Matrix notation:
$$
\frac{d\boldsymbol{\theta}}{d\zeta} = -\frac{1}{\text{Pe}_R} \left( \mathbf{T} \: \boldsymbol{\theta} + \text{diag}\left(\frac{1}{\phi}\right) \mathbf{S} \: \boldsymbol{\theta} \right)
$$


Where:
- $\boldsymbol{\theta}$ is the vector of values $\theta_i(\zeta)$ at all collocation points.  
- $\mathbf{T}$ is the second derivative matrix.  
- $\mathbf{S}$ is the first derivative matrix.  
- $\text{diag}\left(\frac{1}{\phi}\right)$ is a diagonal matrix containing the inverse collocation points.  


### Boundary Conditions
1. Boundary condition at \(r = 0\):
   $$
   \frac{\partial \theta}{\partial \phi} \Big|_{\phi=0} = 0
   $$
   Which translates to:
   $$
   \big[[s^{(1)}]^T \; \theta(\phi_1) \big] = 0
   $$

2. Boundary condition at \(r = R\):
   $$ 
   \dot{q} \Big|_{r=R} = U \big( T \big|_{r=R} - T_\infty \big) = - \lambda_r \frac{\partial T}{\partial r} \Big|_{r=R}
   $$
   In dimensionless form:
   $$
   \frac{\partial \theta}{\partial \phi} \Big|_{\phi=1} = - \frac{R \: U}{\lambda_r} \theta = - \text{Bi} \cdot \theta
   $$
   Which translates to:
   $$
   \big[[s^{(n+1)}]^T \; \theta(\phi_{n+1}) \big] = - \text{Bi} \cdot \theta(\phi_{n+1})
   $$

Which gives a differential algebraic system (DAE).  
By solving for $\theta_1$ and $\theta_{n+1}$ and substituting into the ODEs, the algebraic constraints can be incorporated into the ODEs and a pure ODE system maintained.


Choosing $n=4$.  The collocation points are thus:
$$
\begin{array}{c | c}
i & \phi_i \\
\hline
1 & 0 \\
2 & 0.1127 \\
3 & 0.5 \\
4 & 0.8873 \\
5 & 1 \\
\end{array}
$$

where $\phi_i$ for $i=2, \: 3,\: 4$ are the roots of the Legendre polynomial of third degree, shifted to the domain $0 < \phi < 1$ and  
and $\phi_0$,  $\phi_5$ are the boundaries.

In [57]:

import numpy as np

# n == 4;

# generate shifted legendre polynomial of order 3 and its roots
shifted_leg_poly = np.polynomial.legendre.Legendre( (0, 0, 0, 1), domain=(0,1))
phi = shifted_leg_poly.roots()
#print(phi)

# add boundary collocation points phi_1 = 0 and phi_n+1 = 1
phi = np.insert(phi, 0, 0)
phi = np.append(phi, 1)
print(phi)

[0.         0.11270167 0.5        0.88729833 1.        ]


In [58]:
# generate Q matrix and Q inverse
Q = np.stack( [phi**0, phi**1, phi**2, phi**3, phi**4], axis = 1)
Q_inv = np.linalg.inv(Q)
print(Q)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [1.00000000e+00 1.12701665e-01 1.27016654e-02 1.43149884e-03
  1.61332303e-04]
 [1.00000000e+00 5.00000000e-01 2.50000000e-01 1.25000000e-01
  6.25000000e-02]
 [1.00000000e+00 8.87298335e-01 7.87298335e-01 6.98568501e-01
  6.19838668e-01]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00]]


In [59]:
# generate S matrix
c = np.array([0, 1, 2, 3, 4])
#c = np.atleast_2d(c)
C = np.tile(c, (phi.size,1))
temp = np.append(np.zeros((phi.size,1)), np.stack([phi**0, phi**1, phi**2, phi**3], axis = 1), axis = 1)
C = C * temp
S = C @ Q_inv
print(S)

[[-13.          14.78830558  -2.66666667   1.87836109  -1.        ]
 [ -5.32379001   3.87298335   2.06559112  -1.29099445   0.67620999]
 [  1.5         -3.22748612   0.           3.22748612  -1.5       ]
 [ -0.67620999   1.29099445  -2.06559112  -3.87298335   5.32379001]
 [  1.          -1.87836109   2.66666667 -14.78830558  13.        ]]


In [60]:
# generate T matrix
d = [0, 0, 2, 6, 12]
D = np.tile(d, (phi.size, 1))
temp2 = np.append(np.zeros((phi.size,2)), np.stack([phi**0, phi**1, phi**2], axis = 1), axis = 1)
D = D * temp2
T = D @ Q_inv
print(T)


[[  84.         -122.0631668    58.66666667  -44.60349987   24.        ]
 [  53.23790008  -73.33333333   26.66666667  -13.33333333    6.76209992]
 [  -6.           16.66666667  -21.33333333   16.66666667   -6.        ]
 [   6.76209992  -13.33333333   26.66666667  -73.33333333   53.23790008]
 [  24.          -44.60349987   58.66666667 -122.0631668    84.        ]]
